### ISSUE TITLE
can't build apk when use this plugin

### ISSUE THREAD

**Issue by richardgong1987** [vaenow/cordova-plugin-app-update#28]
can't build apk when use this plugin

**Comment by chaosnote** [comment]
any error message ?

**Comment by developerGroup** [comment]
I use mac book:

```
 ionic start myApp blank


cd myApp


ionic platforms add android

ionic plugin add cordova-plugin-app-update

npm install --save @ionic-native/app-update


then

ionic build android  


```


they will output:


```
:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).

/Users/richard.g/Documents/workspaces/myApp/platforms/android/src/com/vaenow/appupdate/android/CheckAppUpdate.java:6: error: package android.support.v4.app does not exist
import android.support.v4.app.ActivityCompat;
                             ^

/Users/richard.g/Documents/workspaces/myApp/platforms/android/src/com/vaenow/appupdate/android/CheckAppUpdate.java:52: error: cannot find symbol
        int permission = ActivityCompat.checkSelfPermission(activity,
                         ^
  symbol:   variable ActivityCompat
  location: class CheckAppUpdate


/Users/richard.g/Documents/workspaces/myApp/platforms/android/src/com/vaenow/appupdate/android/CheckAppUpdate.java:57: error: cannot find symbol

            ActivityCompat.requestPermissions(activity, PERMISSIONS_STORAGE,

            ^
  symbol:   variable ActivityCompat

  location: class CheckAppUpdate

Note: /Users/richard.g/Documents/workspaces/myApp/platforms/android/src/org/apache/cordova/splashscreen/SplashScreen.java uses or overrides a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

3 errors

:compileDebugJavaWithJavac 
FAILED


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.

> Compilation failed; see the compiler error output for details.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.


BUILD FAILED

Total time: 3.072 secs

Error: /Users/richard.g/Documents/workspaces/myApp/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/Users/richard.g/Documents/workspaces/myApp/platforms/android/src/com/vaenow/appupdate/android/CheckAppUpdate.java:6: error: package android.support.v4.app does not exist
import android.support.v4.app.ActivityCompat;
                             ^
/Users/richard.g/Documents/workspaces/myApp/platforms/android/src/com/vaenow/appupdate/android/CheckAppUpdate.java:52: error: cannot find symbol
        int permission = ActivityCompat.checkSelfPermission(activity,
                         ^
  symbol:   variable ActivityCompat
  location: class CheckAppUpdate
/Users/richard.g/Documents/workspaces/myApp/platforms/android/src/com/vaenow/appupdate/android/CheckAppUpdate.java:57: error: cannot find symbol
            ActivityCompat.requestPermissions(activity, PERMISSIONS_STORAGE,
            ^
  symbol:   variable ActivityCompat
  location: class CheckAppUpdate
Note: /Users/richard.g/Documents/workspaces/myApp/platforms/android/src/org/apache/cordova/splashscreen/SplashScreen.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

```

**Comment by chaosnote** [comment]
@developerGroup 
see issues#17
https://github.com/vaenow/cordova-plugin-app-update/issues/17

guess no import package android.support.v4

**Comment by elysium93** [comment]
I have the same problem，how to solve it？
`:compileDebugJavaWithJavac FAILED


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.


BUILD FAILED

Total time: 2.76 secs

Error: cmd: Command failed with exit code 1 Error output:
C:\Users\Administrator\Desktop\love_xi2\platforms\android\src\com\vaenow\appupdate\android\CheckAppUpdate.java:52: ����: �Ҳ�������
        int permission = ActivityCompat.checkSelfPermission(activity,
                                       ^
  ����:   ���� checkSelfPermission(Activity,String)
  λ��: �� ActivityCompat
C:\Users\Administrator\Desktop\love_xi2\platforms\android\src\com\vaenow\appupdate\android\CheckAppUpdate.java:57: ����: �Ҳ�������
            ActivityCompat.requestPermissions(activity, PERMISSIONS_STORAGE,
                          ^
  ����:   ���� requestPermissions(Activity,String[],int)
  λ��: �� ActivityCompat
ע: C:\Users\Administrator\Desktop\love_xi2\platforms\android\src\org\apache\cordova\splashscreen\SplashScreen.javaʹ�û򸲸����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
2 ������

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
`

**Comment by 1kevinson** [comment]
Hello , 

in terminal insert this command: 
> ionic cordova plugin list 

after in your list of plugin you would see 
> cordova-plugin-app-update 1.3.* "AppUpdate"

do now :
> ionic cordova plugin remove cordova-plugin-app-update

and then it's would be fix !!

now run in your emalator : 
> ionic cordova run android 


I hope this has helped you !

**Comment by timataran** [comment]
Hello, **vaenow**!
Recently I had the same issue, I couldn't build apk with AppUpdate plugin.
I've managed to get it back to work with [some changes](https://github.com/timataran/cordova-plugin-app-update/commit/0bd3bef7d228cd24511b975d825ebe32cba0c056) in plugin code.
Please, take a look. Does this solution have any downsides on your opinion?

**Comment by arthursp** [comment]
resolved with last version ?

**Comment by Amarpret** [comment]
can this plugin work in ionic 1?

**Comment by carlo318** [comment]
Yes, I am using it with Ionic 1  on Android 6.
Still have the issue that some times it works, some other times it hangs at the end of the download (I guess it is not related to Ionic).
See issue #107

**Comment by Amarpret** [comment]
after install plugin when build it show error
![untitled](https://user-images.githubusercontent.com/20854128/45198053-202b4780-b282-11e8-8bbf-94f145c9a616.png)
